#!/usr/bin/env bash
# Build .env.test from GCP Secret Manager + local sa-key.json (secrets never printed).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/.env.test"
PROJECT="${GCP_PROJECT_ID:-}"
if [[ -z "$PROJECT" ]]; then
  echo "ERROR: Set GCP_PROJECT_ID (e.g. export GCP_PROJECT_ID=your-gcp-project-id)"
  exit 1
fi

secret() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT" 2>/dev/null
}

if ! gcloud auth print-access-token &>/dev/null; then
  echo "ERROR: gcloud not authenticated. Run: gcloud auth login"
  exit 1
fi

SA_KEY="${ROOT}/sa-key.json"
if [[ ! -f "$SA_KEY" ]]; then
  echo "ERROR: ${SA_KEY} not found. Download SA key or set SA_KEY_PATH manually."
  exit 1
fi

# Active gcloud account as test super admin (must be Workspace super admin)
TEST_ADMIN="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' | head -1)"
if [[ -z "$TEST_ADMIN" ]]; then
  echo "ERROR: No active gcloud account"
  exit 1
fi

JWT_SECRET="$(secret app-jwt-secret)"
WORKSPACE_DOMAIN="$(secret app-workspace-domain)"
CLIENT_ID="$(secret oauth-client-id)"
CLIENT_SECRET="$(secret oauth-client-secret)"
ALLOWED="$(secret app-allowed-domains 2>/dev/null || echo "$WORKSPACE_DOMAIN")"

if [[ -z "$JWT_SECRET" || -z "$WORKSPACE_DOMAIN" || -z "$CLIENT_ID" ]]; then
  echo "ERROR: Could not read required secrets from project ${PROJECT}"
  exit 1
fi

cat > "$OUT" <<EOF
# Auto-generated by scripts/bootstrap-env-test.sh — do not commit
TEST_SUPER_ADMIN_EMAIL=${TEST_ADMIN}
JWT_SECRET=${JWT_SECRET}
GCP_PROJECT_ID=${PROJECT}
WORKSPACE_DOMAIN=${WORKSPACE_DOMAIN}
GWS_ALLOWED_DOMAINS=${ALLOWED}
SERVICE_ACCOUNT_SECRET_NAME=service-account-key
SA_KEY_PATH=${SA_KEY}
GOOGLE_CLIENT_ID=${CLIENT_ID}
GOOGLE_CLIENT_SECRET=${CLIENT_SECRET}
GOOGLE_REDIRECT_URI=http://localhost:5001/api/auth/callback
CORS_ORIGIN=http://localhost:3000
TEST_MUTATIONS=false
PORT=5001
NODE_ENV=development
EOF

echo "OK: Wrote ${OUT} for ${TEST_ADMIN} @ ${WORKSPACE_DOMAIN}"
echo "Live tests auto-discover groups, drives, and files from your tenant (no manual TEST_* IDs required)."
echo "Run read-only: npm run test:live:read"
echo "Run full suite (API + mutating + E2E): npm run test:all"
